Lesson 3: Functions & Arrays
js-tasks-ru/jsbasic-20210420_xoroshilov pull request #4
Opened 2021-05-02 19:32 UTC by khorosh1lov

- По 1 и 2 задачам вопросов нет.

- Тяжелее всего (почему-то) было с 3ей задачей и функцией camelize(), где трудности возникли с осознанием _«Как убрать - дефисы и сделать после них заглавные буквы, но не трогать первое слово»..._ Чего-то прямо хз. Причём, что нужно использовать связку `split, map, join` было понятно сразу, а вот условие для `map` никак не хотело лезть в голову...

- В 4ой всё прошло гладко. Но есть нюанс: `join('\n');` к методу объединения с "клеем" нет вопросов, всё очевидно. Перевод каретки (строки) вида `\n` тоже всем, даже начинающим разработчикам известен, но вот объединить одно с другим у меня вышло не специально, а как говорится методом _"а что если..."_ и я офигел когда сработало :) Кароче маленький эксперимент и удачный исход. Потом в принципе разобрался. Методу join нужно собрать строку из элементов, клей я указал как перевод строки, собственно всё. Последний элемент массива добавляется в строку и перевода строки не происходит, так как join останавливается на этом.

- В 5ой задаче немного тупил, совсем почему-то вылетело из головы что можно возвращать объект, просто сделав `return { }`, так же, я немного знаком с регулярными выражениями и сделал `split` сразу по 2 сепараторам, я не смог придумать как по другому, увы, но знаю точно что можно, ибо регулярки мы не проходили.

2021-05-02 19:32 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-05-02 20:00 UTC, SinimaWath requested changes

2021-05-02 20:00 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  return names;
Давай упростим:
- Используем map
- В одну строчку
- Деструктуризация

2021-05-02 20:00 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  let validUsers = users.filter(user => user.age <= age);
Это же const :P

2021-05-02 20:00 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  return validUsers.map(user => `${user.name}, ${user.balance}`).join('\n');
Давай тут для практики, тоже попробуем деструктуризацию

2021-05-02 20:00 UTC, SinimaWath commented on 3-module/5-task/index.js
> +    .filter(item => { return Number(item) });
filter -> функция, должна возвращать true/false, в твоем случае: `Number` -> возвращает число или NaN, что может привести к багам(0 - это false). 

Нужно переделать на `isFinite` - к примеру.

2021-05-02 20:03 UTC, SinimaWath commented on 3-module/5-task/index.js
> +    .split(/,| /)
Давай оставим, регулярку - только вынесем ее в глобальную область:
```
const REGEX = /,| /;

function getMinMax() {
..
}
```

Так как на каждый вызов функции, регулярное каждый раз инициализируется. Но можно сделать это один раз в глобальной области

2021-05-02 20:34 UTC, khorosh1lov commented on 3-module/1-task/index.js
> +  return names;
`return users.map(user => user.name);`
В одну строку с помощью map, выглядит круче, согласен. Не совсем понятно про "Деструктуризацию" чего ты пишешь, ибо юзеры в виде объектов и так уже в массиве и этот массив скармливается функции. Не понимаю что еще можно деструктурировать внутри функции :)

2021-05-02 21:08 UTC, khorosh1lov commented
Я совсем не понял где и как в 1 и 4 задачах применять деструктуризацию. В 4ой я понимаю абстрактно, что нужно добиться записи вида `${name}` и `${balance}` вместо` ${user.name} / ${user.balance}`, но не смог понять как массив объектов деструктурировать чтобы потом получить циклический вывод с подстановкой имени и баланса.

2021-05-03 17:03 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  return names;
`return users.map(({ name }) => name)`

2021-05-03 17:03 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  return validUsers.map(user => `${user.name}, ${user.balance}`).join('\n');
({ name, balance }) => ....

2021-05-03 20:35 UTC, khorosh1lov commented
Спасибо большое Влад! 
Еще раз посмотрел твои подсказки и перечитал про Деструктуризацию в учебнике, разобрался. Думаю практикой закреплю со временем.

2021-05-04 18:57 UTC, SinimaWath approved these changes

2021-05-04 18:57 UTC, merged