Lesson 5: Events and Handlers
js-tasks-ru/jsbasic-20210420_xoroshilov pull request #6
Opened 2021-05-10 04:17 UTC by khorosh1lov

1 и 2 задачи оказались очень уж простыми, без вопросов.

Слайдер: не понимаю почему не проходят тесты, вручную всё проверил, всё работает как в примере: [https://course-jsbasic.javascript.ru/](Бангкок Эксперсс), так что возможно моя реализация не подходит, но! Я мог бы сделать через `class` и методы класса карусели, но мы судя по расписанию только в пятницу будем их проходить, не хочу торопить события. В общем не знаю что там тестам не нравится, но работает всё чётко и даже больше - в слайдер можно пихать сколько хочешь слайдов сейчас, хоть 1 и всё будет работать как описано в задаче.

2021-05-10 04:17 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-05-11 15:16 UTC, SinimaWath requested changes

2021-05-11 15:16 UTC, SinimaWath commented on 5-module/1-task/index.js
> +    button.setAttribute('hidden', '');
hidden - стандартный атрибут, давай использовать свойства

2021-05-11 15:16 UTC, SinimaWath commented on 5-module/2-task/index.js
> +    text.toggleAttribute('hidden');
Стандартный аттрибут

2021-05-11 15:16 UTC, SinimaWath commented on 5-module/1-task/index.js
> +  button.addEventListener('click', () => {
Обработчик должен отрабатывать только один раз, когда кнопка скрывается, больше не нужен обработчик

2021-05-11 15:16 UTC, SinimaWath commented on 5-module/3-task/index.js
> +  arrowLeft.addEventListener('click', () => { prevSlide(); });
arrowLeft.addEventListener('click', prevSlide); - нет необходимости в промежуточной функции, в замыкание останется все что нужно

2021-05-11 15:16 UTC, SinimaWath commented on 5-module/3-task/index.js
> +const disableArrows = (...args) => {
args - слишком абстрактное название для аргументов, нужно более конкретное - что там лежит

2021-05-11 15:16 UTC, SinimaWath commented on 5-module/3-task/index.js
> +let   slidePosition = 0;
Эти значения нужно инициализировать в initCarousel.

Так как тесты сначала формируют DOM, а только потом вызывают initCarousel.

В твоем случае:
- ищутся елементы в DOM -> их нет
- В тестах формируется DOM
- В тестах вызывается initCarousel
- Ничего не работает (

2021-05-11 18:09 UTC, khorosh1lov commented on 5-module/2-task/index.js
> +    text.toggleAttribute('hidden');
Только я не понимаю как элегантно, так же одной строкой кода тоглить текст? Если обращаться к элементу `text.hidden` придётся писать дополнительные строчки.

2021-05-11 18:33 UTC, khorosh1lov commented
1 и 3 задачи поправил.

2 задача с toggle вопрос мой открыт :) Не совсем понимаю как это реализовать через обращение по стандартному атрибуту `text.hidden` ибо придётся дописывать больше логики для переключение между `true / false`

2021-05-12 02:09 UTC, SinimaWath commented on 5-module/2-task/index.js
> +    text.toggleAttribute('hidden');
можно вот так `text.hidden = !text.hidden`

2021-05-12 02:13 UTC, khorosh1lov commented on 5-module/2-task/index.js
> +    text.toggleAttribute('hidden');
ого, это блин не стандартная тема :) Я весь инет облазил, перечитал учебник, везде toggleAttribute, а ты предлагаешь что то не стандартное :)

2021-05-12 02:15 UTC, khorosh1lov commented
Исправил

2021-05-13 07:59 UTC, SinimaWath approved these changes

2021-05-13 08:00 UTC, merged