Lesson 7: Complex Components
js-tasks-ru/jsbasic-20210420_xoroshilov pull request #8
Opened 2021-05-21 00:14 UTC by khorosh1lov

Влад! 
Вроде всё сделал, вроде всё работает :)
В 4ой задаче уже делал для себя комментарии, чтобы не запутаться и вспомнить вообще что это такое + использовал твой пример с "тяни-толкаем" на Codepen, ибо не такая уж и простая задача оказалась. Единственных момента по сути два:

1. Мне не нравится как я убираю через `forEach` класс для спанов, нужно мне кажется более элегантное решение, ибо очень много обращений, подскажи пожалуйста.
2. Кастомный ивент создаётся по клику, слушается отдельным лисенером, мне кажется это не правильно, однако если создавать ивент прямо при событии `pointermove` происходит лютая дичь, сотни событий на каждый пиксель движения мыши...В общем тут тоже так и не разобрался, подскажи пожалуйста.

Жду ревью :)

2021-05-21 00:14 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-05-22 00:31 UTC, SinimaWath requested changes
Все круто. 

Есть маленькие замечания

2021-05-22 00:31 UTC, SinimaWath commented on 7-module/1-task/index.js
> +    });
А зачем оборачиваешь в стрелочную функцию?

2021-05-22 00:31 UTC, SinimaWath commented on 7-module/1-task/index.js
> +    });
У тебя _checkRibbonScroll - стрелочная

2021-05-22 00:31 UTC, SinimaWath commented on 7-module/1-task/index.js
> +    const itemId = item.closest(`a`).dataset.id;
Давай все так в верстке откажемся от прямой зависимости от a - и используем data атрибут

2021-05-22 00:31 UTC, SinimaWath commented on 7-module/2-task/index.js
> +    document.addEventListener('keydown', this._onEscButtonPressed);
у тебя тут утечка подписки.

когда модальное окно закрывается, забываешь удалить keydown и click

2021-05-22 00:31 UTC, SinimaWath commented on 7-module/4-task/index.js
> +    };
Давай все таки ввынесем в отдельный метод, такой код немного сложно воспринимать.

Функци _onThumbDrag - сейчас слишком большая

2021-05-22 00:58 UTC, khorosh1lov commented
Всё исправил, прямо совсем мелочи были :)

Неужели прямо хорошо справился? Я не скрываю что смотрел твои CodePen'ы естественно, но не ожидал что косяков будет так мало, учитывая объём задач.

2021-05-22 19:00 UTC, SinimaWath approved these changes

2021-05-22 19:00 UTC, merged