Lesson 8: Server Interaction
js-tasks-ru/jsbasic-20210420_xoroshilov pull request #9
Opened 2021-05-26 19:12 UTC by khorosh1lov

В обще 1 и 3 задачи сделал сам.
2 Подсмотрел.
4ая сделана на ~50%, есть вопросы, возможно подскажешь что-то. Я сделал комменты в файле.

2021-05-26 19:12 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-05-27 03:35 UTC, khorosh1lov commented
Исправил onSubmit на стрелочную функцию, была потеря this, поэтому не мог понять почему экземпляр класса cartIcon не обновлялся при отправке формы. Теперь корзина очищается и "иконка" обновляется.

2021-05-27 04:38 UTC, khorosh1lov commented
Исправил поведение, теперь все на лету обновляется в модалке. Единственный нюанс, жалко что теряется сам созданный класс modal и я не могу использовать публичный  метод close() чтобы закрывать модалку. Пришлось по сути его занового писать внутри onProduxtUpdate, выбирая модаль, удаляя класс с body и делая наглый так сказать remove Dom элементу окна )) 

А хотелось просто modal.close() написать, хе.

2021-05-27 15:43 UTC, SinimaWath requested changes

2021-05-27 15:43 UTC, SinimaWath commented on 8-module/3-task/index.js
> +    const cartItem = Object.assign({}, { product: product, count: 1 });
А зачем тут Object.assign?

Если можно просто обьект создать: `cont cartItem = {}`

2021-05-27 15:43 UTC, SinimaWath commented on 8-module/3-task/index.js
> +    if (existingProduct) { existingProduct.count += amount; } else { return; }
скорее нужно от негативного условия:
```
if (!existingProduct) {
  return;
}

...
```

2021-05-27 15:43 UTC, SinimaWath commented on 8-module/4-task/index.js
> +    let modal = new Modal();
Надо модальное окно сохранить как свойство класса, в этом случае можешь использовать `this.modal`.

И сможешь вызывать методы

2021-05-27 15:43 UTC, SinimaWath commented on 8-module/4-task/index.js
> +  onSubmit = (event) => {
Давай на async/await переделаем

2021-05-27 18:07 UTC, khorosh1lov commented
Готово, всё исправил.

2021-05-27 19:27 UTC, SinimaWath approved these changes

2021-05-27 19:28 UTC, merged